services:
  comets-service:
    build: .
    env_file:
      - .env
    ports:
      - "8082:8080"
    environment:
      - APP_PORT=8082
      - RUN_MIGRATIONS=true
      - USE_REAL_CLIENTS=false
      - AUTH_SERVICE_ADDR=127.0.0.1:50051
      - ORBIT_SERVICE_ADDR=127.0.0.1:50052
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=mydbpass
      - DB_NAME=cometdb
      - SEED_TEST_DATA=false
    depends_on:
      - postgres

  
  postgres:
    image: postgres:15-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "cometdb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "mydbpass"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d commetdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G

## По умолчанию в этой конфигурации используется локальный драйвер docker
volumes:
  postgres_data: